name: Deploy Terraform files to Azure

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
    deployToDev:
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ARM_USE_OIDC: true
            
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            addSpnToEnvironment: true

        - name: Terraform Init
          run: |
            terraform init \
            -backend-config="resource_group_name=tfstate-rg2" \
            -backend-config="storage_account_name=tfstatewai2" \
            -backend-config="container_name=anuworkshop" \
            -backend-config="key=dev"
        
        - name: Terraform Apply
          run: terraform apply -auto-approve -var="env=dev"
     
    deployToProd:
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ARM_USE_OIDC: true
        needs: deployToDev
          
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            addSpnToEnvironment: true

        - name: Terraform Init
          run: |
            terraform init \
            -backend-config="resource_group_name=tfstate-rg2" \
            -backend-config="storage_account_name=tfstatewai2" \
            -backend-config="container_name=anuworkshop" \
            -backend-config="key=prod"
        
        - name: Terraform Apply
          run: terraform apply -auto-approve -var="env=prod"


